microservices:
  orders:
    url: http://localhost:5000
    timeout: 30
    authorization: true
    forward:
      headers: true
      body: true
      params: true

  users:
    url: http://localhost:5001
    timeout: 30
    authorization: false
    forward:
      headers: true
      body: false
      params: true

  inventory:
    url: http://localhost:5002
    timeout: 45
    authorization: true
    forward:
      headers: true
      body: true
      params: true